dist: trusty

language: ruby
cache: bundler

rvm:
  - 2.4.3
  - 2.5.0

notifications:
  email: false

addons:
  apt:
    packages:
    - git-svn

before_install:
  # This is a workaround for a problem with a specific version of bundler and
  # rubygems
  - gem update --system

script:
  - bundle exec rspec --format progress
