dist: trusty

language: ruby
cache: bundler

rvm:
  - 2.4.3
  - 2.5.0

notifications:
  email: false

addons:
  apt:
    packages:
    - git-svn

before_install:
  gem update --system

script:
  - bundle exec rspec --format progress
